In [28]:
import torch

# 假设 batch_latents 是一个包含多个三维张量的列表
a = torch.randn(2, 3, 4)  # 形状 (2, 3, 4)
b = torch.randn(2, 5, 4)  # 形状 (2, 5, 4)
c = torch.randn(2, 2, 4)  # 形状 (2, 2, 4)
batch_latents = [a, b, c]

# 计算第二个维度的最大值
max_dim1 = max(latent.size(1) for latent in batch_latents)  # 第二个维度的最大值

# 对每个 Tensor 进行填充（仅填充第二个维度）
padded_latents = [
    torch.nn.functional.pad(latent, (0, 0, 0, max_dim1 - latent.size(1)), "constant", 0)
    for latent in batch_latents
]

# 基于第一个维度进行堆叠
stacked_latents = torch.cat(padded_latents, dim=0)

print(stacked_latents.shape)  # 输出形状，应该是 (6, 5, 4)

torch.Size([6, 5, 4])


In [26]:
max_dim1

5

In [25]:
a

tensor([[[-0.8071,  1.3985, -0.6701, -1.5767],
         [ 0.3758, -0.0732,  0.0732, -0.5156],
         [ 1.5471, -0.6376, -0.7931,  0.3049]],

        [[-0.1562, -1.1074, -0.3387, -0.1765],
         [ 0.1164, -0.2448, -1.1447, -0.0258],
         [ 0.9395, -0.7757, -1.1107,  0.1880]]])

In [24]:
stacked_latents

tensor([[[-0.8071,  1.3985, -0.6701, -1.5767],
         [ 0.3758, -0.0732,  0.0732, -0.5156],
         [ 1.5471, -0.6376, -0.7931,  0.3049],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000]],

        [[-0.1562, -1.1074, -0.3387, -0.1765],
         [ 0.1164, -0.2448, -1.1447, -0.0258],
         [ 0.9395, -0.7757, -1.1107,  0.1880],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000]],

        [[ 0.0379,  1.9919,  0.0804, -0.8319],
         [ 1.7970, -0.7157, -1.0683, -0.3876],
         [ 1.4193,  0.1243, -0.3534, -0.3106],
         [ 0.4134, -0.0437, -0.7826,  0.3276],
         [-0.5432, -0.1519, -0.5887, -0.2240]],

        [[ 0.6305,  1.0467,  0.6052,  1.6762],
         [ 1.7311,  0.3652,  1.1454, -1.2955],
         [-0.2031,  0.3559, -0.5388, -0.1784],
         [ 0.0429,  0.5070, -0.2623, -0.9959],
         [-0.3980,  0.1308,  0.3514,  0.6875]],

        [[-0.0101,  0.3035,  0.6332,  0.6073],
     

In [19]:
stacked_latents


tensor([[[ 1.2746e-01,  1.1922e+00,  3.4399e-01,  1.3137e+00],
         [-5.9339e-01,  1.7950e+00, -5.5839e-01, -6.1768e-01],
         [ 1.4780e+00, -1.8156e-01,  1.1146e+00, -8.5840e-02],
         [-8.2444e-02, -7.0281e-01, -1.1828e+00, -8.3938e-01],
         [ 2.6087e+00, -1.4187e+00,  6.7597e-01,  1.5850e-03]],

        [[-2.8776e-01,  8.9521e-01, -1.4459e+00,  5.2116e-01],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 1.1049e-01,  8.9829e-01,  3.9984e-01,  1.2490e-01],
         [-1.3378e-01, -6.7671e-01,  4.9730e-01, -1.3999e+00],
         [-5.1278e-01, -7.5560e-01, -1.0368e+00,  7.4515e-02],
         [-1.3729e+00,  1.7007e+00, -4.9021e-01, -1.0797e+00],
         [ 2.4871e-02, -4.4387e-01, -2.7884e-02,  1.3790e+00]],

        [[ 5.7060e-01,  5.3225e-02, -1.5095e+00, 

In [4]:
stacked_latents

tensor([[[-0.5098,  0.8720, -0.6750,  1.0764],
         [-1.1190,  0.2767, -0.4411, -2.1957],
         [-0.5613, -0.1135,  0.2344,  0.5714],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000]],

        [[-0.2739, -1.4796,  0.0251, -1.3894],
         [ 0.0086,  1.2457, -1.1855, -1.1024],
         [ 0.2383,  1.8427,  0.8460,  0.3798],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000]],

        [[-0.1677, -0.3412,  0.1167,  0.3000],
         [-1.4448, -0.5128, -0.0215, -1.0978],
         [-0.8985, -0.2915,  1.1266, -0.1918],
         [-0.3812, -0.3108,  1.7124, -1.1379],
         [-1.2062,  1.9020, -0.4716,  1.1346]],

        [[ 1.2064, -1.3618,  1.0081,  0.0284],
         [-0.6396,  1.1192, -0.7387,  1.2435],
         [ 0.6682, -0.1655, -1.1520, -1.2250],
         [ 0.4401,  0.1402,  2.6655,  0.8387],
         [ 1.7636, -0.6274, -0.6443,  0.4765]],

        [[-2.4891, -0.3024, -0.5551, -0.3372],
     

/home/ckqsudo/miniconda3/envs/SAE/lib/python3.11/site-packages/torch/nested/__init__.py:226: UserWarning: The PyTorch API of nested tensors is in prototype stage and will change in the near future. (Triggered internally at ../aten/src/ATen/NestedTensorImpl.cpp:178.)
  return _nested.nested_tensor(


TypeError: cat() received an invalid combination of arguments - got (Tensor, dim=int), but expected one of:
 * (tuple of Tensors tensors, int dim = 0, *, Tensor out = None)
 * (tuple of Tensors tensors, name dim, *, Tensor out = None)
